# Generated by Django 2.2 on 2019-04-22 03:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('relationtest', '0002_temp1'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='temp1',
            managers=[
                ('manage1', django.db.models.manager.Manager()),
            ],
        ),
    ]
