# Generated by Django 2.2 on 2019-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='MyBlog.Label'),
        ),
    ]
