# Generated by Django 2.2 on 2019-04-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bool_pubdate',
            new_name='book_pubdate',
        ),
    ]
