# Generated by Django 2.2 on 2019-04-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('parrent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytest.Area')),
            ],
        ),
    ]
